### ISSUE TITLE
Detect main frame in `did-stop-loading`

### ISSUE THREAD

**Issue by FWeinb** [atom/atom-shell#1018]
Just like it is possible with the [`did-get-redirect-request`](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#did-get-redirect-request) or [`did-frame-finish-load`](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#event-did-frame-finish-load) it would be great to be able to detect if the main frame was loaded completely (with all sub frames) 

Currently the `did-stop-loading` event is fired for every frame that finished without the ability to differentiate frames from the main window.

**Comment by zcbenz** [comment]
The `did-finish-load` event only emits for main frame, it is just a special case of `did-frame-finish-load`. Have you tried with the latest release?

**Comment by FWeinb** [comment]
I mean't the `did-stop-loading` event instead of `did-finish-load` because `did-finish-load` will be fired before all frames are loaded.

**Comment by zcbenz** [comment]
I think we should add `did-frame-stop-loading` event that has a `isMainFrame` parameter and make `did-stop-loading` only emit for main frame, so we can make the APIs consistent.

**Comment by FWeinb** [comment]
:+1: Would really like that!

**Comment by zcbenz** [comment]
@FWeinb I checked Chromium's code and found that it is not possible to detect main frame in `did-stop-loading` event, because it is not a event of frame, but a event that could be emitted for many reasons.

The only reliable way to detect whether main frame is loaded is the `did-finish-load` event, if you want to detect whether all the frames in page have been loaded, you have to do it yourself in the renderer process, Chromium doesn't provide an API for that.

So I'm closing this since it can not be implemented.
