### ISSUE TITLE
Provide web accessible endpoint listing info on all releases

### ISSUE THREAD

**Issue by springmeyer** [atom/atom-shell#1022]
At the least it should declare the `atom-shell` version, the v8 version, and the process.versions.modules value.

IO.js has offered this (https://iojs.org/download/release/index.json) and it makes knowledge about ABI compatibility transparent and accessible in an automated way. This is important for node-pre-gyp to know which binaries for a given Node C++ addon will work with a given Atom Shell version. refs #mapbox/node-pre-gyp#112 | #533.

**Comment by springmeyer** [comment]
Although even more ideal would be to use a specific, unaltered io.js release inside atom-shell to maintain full ABI compatibility with a given io.js release. Then node-pre-gyp could in fact just use https://iojs.org/download/release/index.json to know the `process.versions.modules` value for a given atom-shell release.

**Comment by paulcbetts** [comment]
You also need to include the name of the executable that Atom Shell is built on, because Windows includes that name in the IAT of built native modules (see #713 for the ugly details). imho, this lessens the utility of node-pre-gyp as a concept, because anyone who renames atom.exe will bust the published binaries :-/

**Comment by imlucas** [comment]
@paulcbetts actually just fixed this for christkv/bson-ext iojs support. See tootallnate/node-gyp#599

**Comment by paulcbetts** [comment]
@imlucas Yeah, this is fixed in Electron too because modules now link to a `node.dll`
