### ISSUE TITLE
Docs on how to adapt native modules for atom-shell

### ISSUE THREAD

**Issue by dcposch** [atom/atom-shell#1031]
Currently, native modules like node-sqlite3 don't work out of the box with apm.
The reason is that atom-shell uses the Chromium version of V8, which is way ahead of the nodejs version of V8 and not ABI-compatible. So such modules either need code changes (in C++) to be compatible with the new V8, or they need to bump their version of `nan` if they're using `nan`.

Here's what I've found so far:
* In the case of node-sqlite3 specifically, they have instructions for how to build for node-webkit in their README, but no corresponding instructions for atom-shell
* Node-webkit has nw-gyp for building native modules that are compatible with NW. I haven't found a way to do that with apm.
* Then, I thought the iojs build tools might help, since iojs also uses a recent version of V8. Turns out [iojs doesn't support native modules yet](https://github.com/iojs/io.js/issues/373)!

Maybe @zcbenz will know how to make it work, since https://github.com/zcbenz/cefode had sqlite3 built in?

**Comment by dcposch** [comment]
Come to think of it, there's an interesting situation here:
1. Official node, which is 0.10.x, uses a really old V8
2. *Everything else* (atom-shell, node-webkit, iojs, Chrome itself) uses current V8
3. Most of the native modules are written against the old V8 API
4. Some native modules, like node-sqlite3, can work with current V8 but only if you use the node-webkit specific build tool (nw-gyp)

We've got to find a way to fix this!

**Comment by dcposch** [comment]
@feross

**Comment by dcposch** [comment]
By the way, I found the this doc: https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md

But it doesn't quite work for node-sqlite3. Looks like I'm not the only one trying to do this! https://github.com/mapbox/node-sqlite3/issues/357

For now I'll try doing it the way mapbox does it, which is apparently to use node-sqlite3 from a different process and not from the renderer process. 

I think a few sentences in the doc above, clarifying what works in atom-shell and what doesn't, would be v helpful!

**Comment by bwin** [comment]
You can give it a try with https://github.com/bwin/aspm
I use it to build node-sqlite3 for atom-shell >= 0.18.0
But you have to use current github master, since the npm version 3.0.4 is missing a patch.
See aspm tests (node-sqlite3 is in the test-suite).

You have to install aspm (from npm) and then you can do:
`aspm install sqlite3 --tarball https://github.com/mapbox/node-sqlite3/archive/master.tar.gz --target 0.19.5 --arch ia32`
--target is the atom-shell version

**Comment by zcbenz** [comment]
@dcposch atom-shell is not compatible with native modules built against Node because of different versions of V8, you can expect the same problem in node-webkit and io.js.

So in order to use native modules you have to follow the [docs](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md) on building them from source, or wait for [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) to support atom-shell.

Usually modules using `nan` can be built against atom-shell without changing anything, for modules that can't be, if they support building with io.js or node-webkit, they should be able to be built against atom-shell with little modifications.

For `node-sqlite3`, @bwin has given a working solution.

> I think a few sentences in the doc above, clarifying what works in atom-shell and what doesn't, would be v helpful!

I think the [Native Node module compatibility](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md#native-node-module-compatibility) chapter should have made things clear.

**Comment by dcposch** [comment]
> So in order to use native modules you have to follow the docs on building them from source

Yeah, that's the plan.

@bwin awesome, thanks! I'll try aspm.

**Comment by zcbenz** [comment]
I'm closing this since things have been made clear.

**Comment by bwin** [comment]
@dcposch did it work for you?

**Comment by dcposch** [comment]
Yes, it works! Thanks again.

**Comment by Serhioromano** [comment]
Since node.js now merged with io.js it uses latest Chromium engine and it is no longer an issue. Is it?

**Comment by jpike88** [comment]
Can someone clarify if this is still an issue?

**Comment by jglover** [comment]
Yes it is still an issue
