### ISSUE TITLE
Native Module: %1 Is Not a Valid Win32 Application

### ISSUE THREAD

**Issue by acidhax** [atom/atom-shell#1075]
Neither https://github.com/agnat/node_mdns or https://github.com/mscdex/cap works in Atom and node-webkit. I get either %1 is not a valid win32 application after recompiling to 32bit, or module didn't self-register if left as 64bit.

How do I fix this once and for all? What steps does it take to have it working?

node -v : v0.10.36
atom versions tried : v0.19.2 / v0.20.7 / v0.21.0

Followed steps here: https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-native-node-modules.md but nothing could fix it.

**Comment by zcbenz** [comment]
How did you install the modules? There are actually several ways to do it in that tutorial.

**Comment by acidhax** [comment]
npm install mdns
./node_modules/mdns/: node-gyp configure build --verbose --target=*atom versions* --arch=ia32 --dist-url=https://atom.io/download/atom-shell

and, apm install

**Comment by paulcbetts** [comment]
`%1 is not a valid win32 application` - this usually means that either:

1. Your module is actually a 64-bit module
1. Your module is a 32-bit module, but it's linking to a 64-bit module

http://www.dependencywalker.com will tell you what's going on

**Comment by zcbenz** [comment]
I looked into both modules and they seem to be linked with external libraries, which as @paulcbetts said are very likely x64 libraries. So before #980 is fixed you have to find a way to make those modules work on 32bit platform.

**Comment by Xosmond** [comment]
Hey I'm facing this problem with a node native module `node-printer`, did anybody solve it? I have tried to run it packaging on win32 ia32 and win32 x64 and either worked.

**Comment by cotufaloschiflones** [comment]
Hello @Xosmond i'm having this issue on windows too with this module (node-printer) as well. Do you have any update?

**Comment by Xosmond** [comment]
@cotufaloschiflones my advice is remove that native module and use a child_process to exec a command line command to print (depending of the OS), node printer looks unmaintained since 2014.

The general advice is that native module are problematic, sometimes needs to be compiled on a windows machine and even with that there are bugs and errors.

**Comment by cotufaloschiflones** [comment]
Hi @Xosmond 
First, I was trying to compile for windows from mi Mac and I had that problem, but after some readings I figured out how to proceed, and after all I can say that I got it. Yesterday I spent all day setting up a windows virtual machine in my (other) Linux laptop (I used my linux laptop just because my mac was exhausted in storage...). I was having too a problem with the preloadScript from electron main process in windows, Cant found the script, it was solved too.

Anyway, I think the library node printer from @tojocky is well maintained, in other hand in the electron-builder documentation they say that you should compile in native for natural reasons. Once you will have it, you'll see that it's a cleaner and pragmatic solution ...

This was my entire process, I hope it helps to someone having the same issue:
- Get VirtualBox (or Parallels but is not free)
- Get iso for W10
- Create a VM with this W10 iso, and you should give to this VM some storage (because some dependency that you'll need to compile), I have assigned 60gb to this VM
- Once I had that VM running, I just installed in that machine  Visual Studio 2017 (with their build-tools included, it's necessary)
- And then, I used CMD to make the rest
- Install NodeJS (and NPM, but it comes with)
- Install node-gyp globally
- Install Python 2.7
- Clone your project from git (in my case)
- npm i (in your project), you should have as npm dependency in your package.json the module electron-builder of course. (here I had some troubles because when node-gyp tried to rebuild printer to generate the binary for windows it was failing, this was because it was imposible to find the python executable, so if you face this problem you should add it like:`npm config set python "c:\Python27\python.exe"` in my case )
- Then try again npm i and Voila!

**Comment by Xosmond** [comment]
@cotufaloschiflones Hey, great that it worked for you, in my case, I tried it just that day (a week before) and i got it compiled but I got an error on running time and I didn't know how to solve it because It was raised inside the native module (this error only occurred on windows). So I tried that other way and it was more easy and I didn't need a windows VM.

**Comment by qasimlucky** [comment]
krdayo solve oaa
