### ISSUE TITLE
incorrect behavior of require() from Renderer with "./abc" paths

### ISSUE THREAD

**Issue by teleclimber** [atom/atom-shell#1162]
Say I have a project structured like so:

```
project/
    index.html
    subdir/
        a.js
        b.js
```

If I include `a.js` in `index.html` using a `<script>` tag, and `a.js` requires `b.js` like this: `require("./b.js");` I get a "module not found" error.

However if I move `index.html` into `subdir/` (and adjust the `<script>` tag naturally) then `a.js` successfully requires `b.js`.

If I set a breakpoint in `module.js` at `Module._resolveFilename` it appears the `parent` passed when requiring `b.js` is the `index.html`, not `a.js`, so it's looking for `b.js` in the same directory as `index.html`. It seems `a.js` should be the `parent` when requiring `b.js`.

**Comment by zcbenz** [comment]
The scripts loaded by `<script>` are loaded under `index.html`'s context, so their module search paths are exactly the same with `index.html`. It can not be fixed because this by design in every browser, if you want to have expected module search paths in your scripts you have to load them with `require`.
