### ISSUE TITLE
sessionStorage not quite working as it should?

### ISSUE THREAD

**Issue by shrewdlogarithm** [atom/atom-shell#1184]
I've been using localStorage to pass data between 2 BrowserWindows (both loaded from file:// so they share data AOK) - but I realised that I don't need the data once the App is closed so I switched to sessionsStorage and - it doesn't work...

It seems sessionStorage is unique to a Window session and not the App session - which I guess I can understand but at the same time it's not really how it's supposed to work (if multiple WIndows share localStorage they should also share sessionStorage?)

p.s. I'm aware I can use remote.getGlobal() to share data but I've found that to be noticeably slower when there's a lot of data - an order of 2-3 times slower in some cases - but that's probably another issue entirely?

**Comment by zcbenz** [comment]
In atom-shell, in order to improve stability and reduce complexity, each window runs the web page in its own renderer process, which is separated with others. This unfortunately makes each window has its own session even when the windows are visiting the same site.

The localStorage stores data in disk for each site, so it is not affected by this.

I'm closing this as won't fix since this is an expected side effect.

> p.s. I'm aware I can use remote.getGlobal() to share data but I've found that to be noticeably slower when there's a lot of data - an order of 2-3 times slower in some cases - but that's probably another issue entirely?

The `remote` module doesn't return serialized objects, instead it returns proxy objects, and when you visit the members of a proxy object you would end up sending IPC messages. So using `remote` to share objects might end up with lots of IPC calls, which will be quite slow.

You can serialize objects to string when sharing them, or just use `ipc` module to explicitly send them.

**Comment by shrewdlogarithm** [comment]
I thought the 'separate process' probably related to sessionStorage (the main reason I'm using atom-shell is the separate processes - it means memory is freed when a window is closed which node-webkit doesn't do)

I can easily simulate sessionStorage by removing localStorage on window close/app exit or even on startup the next time around anyway so it's no big deal.

The 'proxy object' thing explains the staggering amount of IPC data in the profiler (I had an object with 10s of 1000s of properties - many of which were objects in their own right) - it was impossible to navigate through it to see where the 'real work' was being done, so I'll try serializing the object - thanks again!
