### ISSUE TITLE
IPC off-method

### ISSUE THREAD

**Issue by Trixt0r** [atom/atom-shell#1239]
Is there any possibility to remove a handler for a specific ipc message?

If not, is there any plan to support such a functionality?

-Trixt0r

**Comment by bwin** [comment]
It's an EventEmitter (https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener), so try
```javascript
ipc.removeListener('blah', handler);
```

**Comment by Trixt0r** [comment]
Thanks, this worked!

**Comment by Kyprus** [comment]
I was looking for an ipc.off method as well and came across this. I think it would be nice if you could just `ipc.off(channel)` to remove all handlers for that channel. Is that something that could be considered?

**Comment by Mingling94** [comment]
For future readers, addressing @zlangbert's question, `ipc.removeAllListeners(channel)` should do it.

**Comment by chrisnojima** [comment]
It may be valuable to add this to the documenation

**Comment by Akamaozu** [comment]
:+1: add to documentation

**Comment by derwaldgeist** [comment]
+1 also assumed there was an `off` method.

**Comment by MarshallOfSound** [comment]
@derwaldgeist There isn't anything to +1 here, the `ipc` module is a standard node.js `EventEmitter` 😄 

https://nodejs.org/api/events.html#events_class_eventemitter

**Comment by Hammster** [comment]
@MarshallOfSound Not entirely true, the EventEmitter on the render side of things uses the `events@2.1.0` package which has the node 9.4 EventEmitter API. `.off` was introduced with node 10.0.0 and that is only covered by `events@^3.0.0`

I was not sure if this should be opened as another Issue though.

**Comment by MarshallOfSound** [comment]
@Hammster By the renderer side of things I think you are referring to sandboxed renderers where the preload script is browserified and therefore instead of getting nodes `events` module you get the browser-impl (`events@2.1.0` as you mentioned).

We don't strictly control that dependency as it comes through browserify 🤔 If you think that we should look at upgrading that dependency _somehow_ through browserify then please raise a new issue detailing that 🙇

**Comment by Hammster** [comment]
I will do so, thank you for taking the time to look into it 👍
