### ISSUE TITLE
Change menubar/item color in Windows?

### ISSUE THREAD

**Issue by popopome** [atom/atom-shell#1250]
Can I change menubar color or item's color in windows?
I can't find right guide in windows environment.

Looks like Bracket has no trouble to change those colors.

Thanks.

**Comment by bwin** [comment]
Not sure if I understand you correctly (you could provide a screenshot of brackets doing it).
But I don't think it's possible with native menus.

**Comment by bwin** [comment]
So the question is: can this be accomplished cross-platform? Otherwise it's up to debate, how many platform-specific things should go into atom-shell core. But there are some already, so this probably wouldn't kill us...

**Comment by popopome** [comment]
When I looked into source code, there is special code for X11. I believe window can also have same sort of code. 
[https://github.com/atom/atom-shell/blob/e98953a5a563648a69b6cb8535d1f27febeec887/atom/browser/ui/views/menu_bar.cc#L33-L46](https://github.com/atom/atom-shell/blob/e98953a5a563648a69b6cb8535d1f27febeec887/atom/browser/ui/views/menu_bar.cc#L33-L46)

**Comment by zcbenz** [comment]
It is possible to achieve it with _considerable_ work, but the menu API in atom-shell meant to show __native__ menus, if you want custom menus, you should implement it with HTML and CSS, just like what Brackets did.

So I'm closing this as won't fix.

**Comment by waynebloss** [comment]
Native menus *are* customizable, so what you're actually offering is a single, fixed native menu implementation.

Being able to change the color of a menu is important in Windows. Very few applications on Windows leave the default menu bar color as the default, so Electron is practically useless for people wanting to build Windows apps that look nice.

Without this feature, there's no reason for me to use Electron because I'll have to re-implement menus in HTML to make them look good. If I actually want a *good looking* native app, I might as well just use WinForms with either CefSharp or the WebBrowser control.

**Comment by waynebloss** [comment]
The question should not be *can we implement it so it's cross platform* in my opinion.

The question should be *is it important to implement on any platform* and the answer to that is yes. It's important for Windows.

It's not important for OS X because OS X menus are not part of the application window. Therefore, the system colors don't clash with the visual style of the window.

If you always choose the lowest common denominator, Electron won't be a hybrid environment worth using and it will suck on all platforms kind of like the web in general.

**Comment by paulcbetts** [comment]
> Being able to change the color of a menu is important in Windows. Very few applications on Windows leave the default menu bar color as the default

Yep! And they're all owner-drawn, custom menus. Implementing our own one-off, custom menus with the sole capability of changing a background color as their distinguishing feature seems ill-advised

**Comment by waynebloss** [comment]
It's a standard and widely used feature for high level Windows desktop SDKs though. Saying that it's custom or owner-drawn doesn't mean much when it amounts to one or two simple setting for background/foreground color and maybe a third one for a background image.

The code I'm looking at for searches like [win32 change menu color](https://www.google.com/search?q=win32+change+menu+color) doesn't seem terribly difficult.

I guess the bottom line is, if you don't want to do the work because you think it's too much effort to add a few Menu properties that are only useful on Windows - would you consider looking at pull requests to add such a feature?

**Comment by waynebloss** [comment]
If you just don't want to cater to Windows - I get that, but it seems like you're already catering to OS X where necessary with things like a special object model for their wonky (IMO) global menu system.

Menus are just attached to their windows in Windows, so allowing just the most basic customizations on them would go a long way.

**Comment by waynebloss** [comment]
Here's an example using WinForms - I customized this window's menu, toolbar and splitters by setting BackgroundColor and ForeColor to a different system color. Other than that, I had to do very little work to make a decent "dark mode". If I wanted to get this basic feature in Electron, I'd have to build a whole menu system with HTML/CSS/JS.

(The main content block there is a WebBrowser control that points to this [chrome-tabs demo](http://adamschwartz.co/chrome-tabs/).)

![2015-12-18 21_54_24-darkmenudemo](https://cloud.githubusercontent.com/assets/623736/11910916/05867986-a5d3-11e5-94e2-dd454b326c4b.png)

![2015-12-18 21_54_34-settings](https://cloud.githubusercontent.com/assets/623736/11910917/09c8b4dc-a5d3-11e5-8c9f-b1a7737d9c4b.png)

So that's my final argument for this topic. I understand if you don't want to do the work, but I would like to know if you'll consider pull requests for a feature or two like this. Thanks for all your efforts.

Off-topic - I'd really like to see icons in menus too.

**Comment by paulcbetts** [comment]
We'll consider pull requests for this feature.

**Comment by thisKai** [comment]
I know this issue is closed but I noticed that chromium's menus on windows are also owner drawn, they do not match any of the native windows menu styles.

I'm no C++ guy yet but I dug around a bit out of curiosity and this file looks promising: [menu_bar.cc](https://github.com/electron/electron/blob/master/atom/browser/ui/views/menu_bar.cc)
On line 53 and 54 is the following code:
```C++
#if defined(OS_WIN)
  background_color_ = color_utils::GetSysSkColor(COLOR_MENUBAR);
```
if I change `color_utils::GetSysSkColor(COLOR_MENUBAR);` to `SkColorSetARGB(255, 0, 0, 0);` the menubar becomes black, but the text stays black.

If I have any free time I'll keep on digging but if this turns out to be a useful clue for anyone else I'd be even happier :)

**Comment by 4O4** [comment]
> We'll consider pull requests for this feature.

Well, I guess it's time for me to pick up the slack 😃  I'm new to Electron's c++ codebase but I spent a some time during last week to explore and get to know it in order to implement this. I don't know yet when it's going to be completed but I won't easily give up because that's the feature I'm really missing. 

Proof of concept screenshot:
![poc-vscode-dark-menubar](https://user-images.githubusercontent.com/4274691/31139441-d726a13a-a871-11e7-9563-f8974759075c.png)

I'm going to create a pull request as soon as I come up with some clean and usable implementation.

**Comment by XueWei** [comment]
Although this thread is about menu color, I'd ask if there is any way to change the default font of menu for CJK languages?

**Comment by 4O4** [comment]
@XueWei I'm afraid that this is a bit more problematic. Looks like the only method  I found in sources which can be used to set the font is deprecated and scheduled for removal in Chromium (or already removed). See: https://bugs.chromium.org/p/chromium/issues/detail?id=633986

**Comment by steffanhalv** [comment]
@sdj01044 have you already created the pull request?
