### ISSUE TITLE
API feedback: require should have no side effects

### ISSUE THREAD

**Issue by maxogden** [atom/atom-shell#1272]
(putting on my node.js module API hat here)

Today I went to `require('screen')` in my app and got `Can not initialize "screen" module before app is ready`

This breaks common node app conventions, in which require()s are put at the top of the file. This is for a few reasons -- since require() is sync I/O it's good to not hide require() calls down in the code where they may be overlooked. Another reason is purely as a convention, as developers trying to read code and asking e.g. 'where did this `screen` var come from...` will start by looking at the top of the file.

IMO `require('screen')` should not initialize anything, it should return a constructor. Similarly, the behavior of `require('app')` is pretty weird, as it seems simply requiring it is an implicit initialization.

**Comment by zcbenz** [comment]
The problem is atom-shell allows running code on early stage of application to make it possible to hijack Chromium's internal settings, and it is not possible to initialize some APIs at that time. For `screen` module, returning a constructor would be quite weird because there is only one `screen` instance, lazy-initializing when methods are called is another option, but it would make things much more complicated. 

After https://github.com/atom/atom-shell/issues/387#issuecomment-82073846 we will not use `require` to use APIs, but some APIs would still require initialization after the `ready` event of `app`. It doesn't actually solve the problem, but I hope it can make code more clear.
