### ISSUE TITLE
RFC: The names 'client-side' and 'browser-side' are confusing

### ISSUE THREAD

**Issue by ArtskydJ** [atom/atom-shell#1287]
Requesting comments.

When I was reading through atom-shell's documentation, and I found the terms `client-side` (sometimes `renderer`) and `browser-side` confusing. (E.g. In [docs/tutorial/quick-start.md](https://github.com/atom/atom-shell/blob/master/docs/tutorial/quick-start.md#the-browser-side).)

Is this just me?

I suggest the terms `front-end` and `back-end`. This sticks with the client-server analogy, and is less confusing (IMO).

I volunteer to make a PR to the docs if people think this is reasonable.

**Comment by bwin** [comment]
Once you're getting used to, it's ok (and makes sense). But it's still a problem for anyone new to atom-shell.

(On second read I realized that you called it "client-side" and I would call it "renderer-side", so yeah, it's confusing.)

I'm in favor of renaming it. It removes the barrier when diving into Atom-Shell. I'm ok with "frontend" & "backend" (I would remove the dashes.)
Let's see what others think.

**Comment by mark-hahn** [comment]
I have read the docs multiple times over the last year and I still have no
idea which is which.  It is uber-confusing.

**Comment by bwin** [comment]
Hi Mark, what names would you suggest? Or are you ok with "frontend" & "backend" (or maybe with the dashes as in the original proposal)?

**Comment by zcbenz** [comment]
I don't like "frontend" and "backend", they implies traditional Node.js server-client architecture, which is not true for atom-shell, so I'm afraid it would cause much more confusions.

I think we should follow [Chromium's terms](http://dev.chromium.org/developers/design-documents/multi-process-architecture) to use "browser process" and "renderer process", and don't use "client-side" anywhere. We should also remove the comparison with Node.js's server-client architecture, it seems that comparing apple to orange only causes confusions. 

Or we can just ignore everything about Chromium and use "main script" and "web page" instead, so "main script" is a traditional Node.js script with atom-shell's built-in APIs, and "web page" is normal web page that runs in `BrowserWindow` but with Node.js APIs.

**Comment by mark-hahn** [comment]
> I think we should follow Chromium's terms
<http://dev.chromium.org/developers/design-documents/multi-process-architecture>
to
use "browser process" and "renderer process",

In my mind, a browser does rendering, so these two terms pretty much mean
the same thing.  So that wouldn't help me at all.  (I think I may be a
worst case here {grin}).

I'm not good at making up names.  I think the key is to figure out what
each one actually does.  Can someone more knowledgable than me make two
lists, each just 3 or 4 items long, that tell what major functions each one
does?

**Comment by bwin** [comment]
Ok, "frontend/backend" is off the table.
+1 for not using "client-side" anymore (and thus avoiding 2 names for the same thing).
But the problem would still persist as "browser/renderer" is what confuses people. Maybe it's enough to just explain it in a better way?
I personally don't like "main script" & "web page", but I admit that (at least IMHO) it's much clearer than "browser/renderer" to someone who hears/reads it the first time.
Still interested to hear more opinions. @paulcbetts, @deepak1556, @kevinsawicki any thoughts?
Are even tthat many people confused that there is a real need to change names?

**Comment by mark-hahn** [comment]
> I personally don't like "main script" & "web page",

That works well for me.  Now that I think about it, in my mind it is "node"
and "page".  I think these are good concepts but fancier words that mean
the same thing would be better.

**Comment by mark-hahn** [comment]
"Script" is bad in any context since both run javascript.

**Comment by zcbenz** [comment]
Yeah "browser" is confusing, maybe we can use "main process" or "UI process"? These terms are also reasonable under Chromium's context.

**Comment by bwin** [comment]
@mark-hahn
> Can someone more knowledgable than me make two lists [...]

I'm not sure, if I qualify, but let's try (BTW correct me if I'm wrong or else I'm just confusing people more):
**browser**: This is the guy that creates windows, creates systray-icons, auto-updates, registers protocols and handles the IPC. (I think of it as Chrome/Firefox/etc., the core app.)
**renderer**: Everything that's visible. The UI stuff inside the window. (Your good old web-page, but with node.)

Yeah, it's not a really list...
BTW if my explanation is wrong, count that as +1 for changing names.

> Now that I think about it, in my mind it is "node" and "page".

Yeah, but we got node-integration in the "page" so that's more confusing.

**Comment by mark-hahn** [comment]
This thread has gotten me even more confused. Can someone tell me where
each of these things run, or happens?  Use the old current names.  For
example I know the answer to the first one, JS, is in both.

- js
- node
- dom access
- dom rendering
- ipc master
- OS window accessible

**Comment by paulcbetts** [comment]
I think that we should stick with the Chromium names, but always describe right after we mention "browser", "comma, a node.js runloop where the app is started" or something to this effect

**Comment by bwin** [comment]
> This thread has gotten me even more confused.

That was the plan.
Just kidding.

> Can someone tell me where each of these things run, or happens? [...]

As there is a high probability *I* confused you, I leave that open to someone else. Also I apologize.

> but always describe right after we mention "browser", "comma, a node.js runloop where the app is started" or something to this effect

I don't like the "always" in your proposal. If we recognize that we have to explain it everytime we mention it, we may need a better name. If we're going to stick with the names, a single "browser-vs-renderer"-doc would be better IMO.

**Comment by paulcbetts** [comment]
Yeah, "Always" was perhaps a bit hyperbolic (though we could always link "browser" and "renderer" to our "browser-vs-renderer" page)

**Comment by ArtskydJ** [comment]
> If we're going to stick with the names, a single "browser-vs-renderer"-doc would be better IMO.

I don't think stating which is which, clearly, in one place will remove the confusion. When I read the quick start guide, it was quite clear which was which, but when I read the rest of the docs, it didn't stick.

*****

> I think we should follow Chromium's terms to use "browser process" and "renderer process", and don't use "client-side" anywhere. We should also remove the comparison with Node.js's server-client architecture, it seems that comparing apple to orange only causes confusions.

...
> In my mind, a browser does rendering, so these two terms pretty much mean
the same thing.

...
>Yeah "browser" is confusing, maybe we can use "main process" or "UI process"? These terms are also reasonable under Chromium's context.

I like the terms "renderer", and "main process", and I think they make a lot of sense. I also like the idea of removing references to the "client-side".

Is anyone opposed to these? Any more suggestions?

**Comment by deepak1556** [comment]
i am pretty much aligned with "browser" and "render" process, since the codebase is pretty much straight forward to it. @mark-hahn 

* Node runtime is started by the browser process / the main process and thereafter its just context switching happening inside each render process you create and each render process is a like a new tab .

* DOM rendering and accessing are taken care of by blink which is instantiated in each render process

* Since render process is specific to just the tab , all OS related stuff should be taken care of by one single process ( main/browser process) .. You dont want GUI related stuff affected by multiple processes nw ;)

**Comment by ArtskydJ** [comment]
Maybe the main reason to move away from using the term "browser-side", is that the [`browser-window` module](https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md) has a misleading name.

From the main/browser process, you create a `BrowserWindow` instance, that is actually a renderer instance. :confused:

**Comment by YuriSolovyov** [comment]
node-side / web-side / shell-side ? renderer + main process ok for me too.
It seems like almost anything other than browser / renerer would be better, because now it looks like they do the same thing, and your first thought will probably be the wrong one, or at least rename one of them, so you can figure out which is which with simple math :)

Maybe we need our own terminilogy?
Like Controller ("Main process") + Views ("Renderer processes") or something like that.

**Comment by bwin** [comment]
Are we really done here already? (Just asking)

**Comment by ArtskydJ** [comment]
From what I could tell, everyone was ok with 'main process', and 'renderer process'. So I made the PR.

Please voice concerns, everyone!
