### ISSUE TITLE
Problem when running atom-shell app from bash on windows, using atom-shell that's inside of the app directory.

### ISSUE THREAD

**Issue by KamilSzot** [atom/atom-shell#1289]
Minimal test case for this issue is here: https://github.com/KamilSzot/atom-shell-windows-bash-problem

Windows bash attempts to use slashes instead of backslashes and that probably interferes somehow with path calculations. Maybe there's some point there is a relative path calculated between directory where atom-shell lies and where the application lies?

**Comment by deepak1556** [comment]
Sweet bug, thanks for finding it out. The problem is we bypassed require cache by generating two different id's for the same module. Require system works first by looking up module.paths and then module.filename is used if its a relative lookup https://github.com/iojs/io.js/blob/6fc5e953547bfbdf97bc380d4bfc471e3378fad9/lib/module.js#L202 . And the culprit was `module.concat` which generated case sensitive drive letters on mingw.

code:
```
var Module = require('module')

var path = require('path')

var filename = path.normalize(window.decodeURIComponent(__filename))

var dirname = path.dirname(filename)

console.log(filename)

console.log(module.paths.concat(Module._nodeModulePaths(dirname)))
```

**output on mingw :**
```bash
[6876:0324/200528:INFO:CONSOLE(12)] "F:\github\atom-shell-windows-bash-problem\i
ndex.html", source: file:///F:/github/atom-shell-windows-bash-problem/app.js (12
)
[6876:0324/200528:INFO:CONSOLE(14)] "f:\github\atom-shell-windows-bash-problem\n
ode_modules\atom-shell\dist\resources\atom.asar\renderer\lib\node_modules,f:\git
hub\atom-shell-windows-bash-problem\node_modules\atom-shell\dist\resources\atom.
asar\renderer\node_modules,f:\github\atom-shell-windows-bash-problem\node_module
s\atom-shell\dist\resources\atom.asar\node_modules,f:\github\atom-shell-windows-
bash-problem\node_modules\atom-shell\dist\resources\node_modules,f:\github\atom-
shell-windows-bash-problem\node_modules\atom-shell\dist\node_modules,f:\github\a
tom-shell-windows-bash-problem\node_modules\atom-shell\node_modules,f:\github\at
om-shell-windows-bash-problem\node_modules,f:\github\node_modules,f:\node_module
s,F:\github\atom-shell-windows-bash-problem\node_modules,F:\github\node_modules,
F:\node_modules,F:\github\atom-shell-windows-bash-problem\node_modules,F:\github
\node_modules,F:\node_modules", source: file:///F:/github/atom-shell-windows-bas
h-problem/app.js (14)
```

**output on other shells (cmd, cygwin):** 
 ```bash
[11436:0324/200512:INFO:CONSOLE(12)] "F:\github\atom-shell-windows-bash-problem\
index.html", source: file:///F:/github/atom-shell-windows-bash-problem/app.js (1
2)
[11436:0324/200512:INFO:CONSOLE(14)] "F:\github\atom-shell-windows-bash-problem\
node_modules\atom-shell\dist\resources\atom.asar\renderer\lib\node_modules,F:\gi
thub\atom-shell-windows-bash-problem\node_modules\atom-shell\dist\resources\atom
.asar\renderer\node_modules,F:\github\atom-shell-windows-bash-problem\node_modul
es\atom-shell\dist\resources\atom.asar\node_modules,F:\github\atom-shell-windows
-bash-problem\node_modules\atom-shell\dist\resources\node_modules,F:\github\atom
-shell-windows-bash-problem\node_modules\atom-shell\dist\node_modules,F:\github\
atom-shell-windows-bash-problem\node_modules\atom-shell\node_modules,F:\github\a
tom-shell-windows-bash-problem\node_modules,F:\github\node_modules,F:\node_modul
es,F:\github\atom-shell-windows-bash-problem\node_modules,F:\github\node_modules
,F:\node_modules,F:\github\atom-shell-windows-bash-problem\node_modules,F:\githu
b\node_modules,F:\node_modules", source: file:///F:/github/atom-shell-windows-ba
sh-problem/app.js (14)
```

 So we loaded `dep` from two different path ids, hence the reload. The workaround when you made everything relative worked because everything was loaded via module.filename , so no duplicate ids

/cc @zcbenz

**Comment by deepak1556** [comment]
The solution i can think of is to do `Module._nodeModulePaths(global.__dirname).concat(module.paths)` instead of the other way around, would like to hear other suggestions.

**Comment by zcbenz** [comment]
> The solution i can think of is to do Module._nodeModulePaths(global.__dirname).concat(module.paths) instead of the other way around, would like to hear other suggestions.

This will make calls like `require('app')` to prefer users' `app.js` instead of atom-shell's `app` API.

And this behavior is actually expected in io.js/Node.js, there was a PR in Node (https://github.com/joyent/node/pull/6774) to solve this but not accepted, and in io.js they used to make driver letter lower case (https://github.com/iojs/io.js/commit/f6e574018090ed4d63596b8a3bb614f8f48b6267) to solve this, but then reverted at https://github.com/iojs/io.js/pull/100.

So even though it causes confusions, I think we had better keep the same behavior with io.js/Node.js.

**Comment by deepak1556** [comment]
:+1:
