### ISSUE TITLE
Allow Atom.exe to be renamed via delay loading

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#1315]
https://github.com/iojs/io.js/pull/1251 might be a great PR to apply to Atom Shell too - this would mean that Windows users won't have to rebuild the app from scratch to rename the EXE

**Comment by zcbenz** [comment]
That change is in node-gyp, so once it got released in npm we will have it for free.

**Comment by paulcbetts** [comment]
@zcbenz I'm not so sure, check out https://github.com/iojs/io.js/blob/3d46fefe0cb5abf45bb6a21e5d0a377c58f0f896/deps/npm/node_modules/node-gyp/src/win_delay_load_hook.c, I think 'atom.exe' at least has to be added to that list - either that, or we start compiling modules against an internal copy of io.js that always matches Atom's version (which we can certainly already do) - right now, atom.exe definitely shows up in the IAT for node modules

**Comment by zcbenz** [comment]
@paulcbetts I think it means if the the process loading the library is `iojs.exe` or `node.exe` then go to the original routine (which verifies the process's name matches the IAT of node modules), otherwise it tells Windows to load dll for current process (which skips the verification). According to iojs/io.js#1251 certain native modules can not be loaded in the latter way.
