### ISSUE TITLE
codesign fails on Yosemite 10.10.3

### ISSUE THREAD

**Issue by hongrich** [atom/atom-shell#1396]
After upgrading OS X to 10.10.3 and Xcode to 6.3 yesterday, it seems that signing the entire app bundle with `--deep` no longer works. Signing the included frameworks and apps individually according [this](http://furbo.org/2013/10/17/code-signing-and-mavericks/) fixes the problem. Related to #171 and #720

**Comment by asamiller** [comment]
I'm also having an issue signing after updating to 10.10.3 and Xcode 6.3. I'm running:

`codesign --verbose --deep --force --sign "<DEV ID>" build/Atom.app`
and get
`build/Atom.app: invalid or unsupported format for signature
In subcomponent: /Users/asa/app/Atom.app/Contents/Frameworks/Squirrel.framework`

**Comment by zcbenz** [comment]
I think signing individual frameworks and apps is always the correct way to go. I'm closing this since this is a problem of OS X, not something we can fix in atom-shell.

There are also some instructions on code signing in nw.js's issues:
https://github.com/nwjs/nw.js/issues/3258
https://github.com/nwjs/nw.js/issues/616
