### ISSUE TITLE
Screen not working in 0.20.3

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#994]
This doesn't work in the latest version of atom-shell: `var size = Screen.getPrimaryDisplay().workAreaSize;`

If I have that line, the app doesn't load at all. But works in older versions of atom-shell.

Has something changed? and the docs haven't been updated?

**Comment by bwin** [comment]
`require('screen').getPrimaryDisplay().workAreaSize` works in 0.20.5

**Comment by bwin** [comment]
Just a tip: if you're having problems with atom-shell not even loading, try
- starting from the command line. this way you get a little bit of output and can probably find out whats going on
- or if you just want to test little snippets, do it in the devtools-console

BTW, about your issue: I think you always had to `require('screen')` since you want atom-shells screen module not chromiums Screen.

**Comment by zcbenz** [comment]
v0.20.4 has fixed a crash in `screen` module, please reopen if you still see it in latest version.
